[modeshape]
SMIG-D2043 ansible_host=10.15.210.43
[pmc]
SMIG-D2044 ansible_host=10.15.210.44
SMIG-D2045 ansible_host=10.15.210.45
[portal]
SMIG-D2046 ansible_host=10.15.210.46
SMIG-D2047 ansible_host=10.15.210.47
SMIG-D2048 ansible_host=10.15.210.48
[web]
SMIG-D2049 ansible_host=10.15.210.49
[activemq]
SMIG-D2044 ansible_host=10.15.210.44
SMIG-D2045 ansible_host=10.15.210.45

[ora_db]
VBLDIOR-D1136 ansible_host=fxoutma.oracle.ahbint.aok

[ora_db:vars]
# oracle_port=1533
oracle_user=p_config
oracle_pass=password
oracle_sid=fxoutma
ansible_user=ora19
oracle_home=/oracle/19
sql_plus=/oracle/19/bin/sqlplus

[XOUT_HB:children]
portal
pmc
web
activemq
modeshape

[XOUT_HB:vars]
ansible_user=xout-adm
ansible_ssh_private_key_file=/home/xout-adm/.ssh/xout-adm-hb

[all:vars]
#ansible_python_interpreter=/usr/bin/python3
xout_environment=HB_MIGRATION
repo=/work/dms/rollout
udu_context=PRUEF
kasse=AHB
