[modeshape]
SPROD-XO-1F020  ansible_host=10.15.31.20
[activemq]
SPROD-XO-1F021  ansible_host=10.15.31.21
SPROD-XO-1F022  ansible_host=10.15.31.22
[pmc]
SPROD-XO-1F021  ansible_host=10.15.31.21
SPROD-XO-1F022  ansible_host=10.15.31.22
[portal]
SPROD-XO-1F023  ansible_host=10.15.31.23
SPROD-XO-1F024  ansible_host=10.15.31.24
SPROD-XO-1F025  ansible_host=10.15.31.25
[web]
SPROD-XO-1F026  ansible_host=10.15.31.26
[tobi]
SPROD-XO-1F027  ansible_host=10.15.31.27

[ora_db]
SPRODI-OR-29018 ansible_host=fxoutp.oracle.ahb.aok

[ora_db:vars]
oracle_user=p_config
oracle_pass=password
oracle_sid=fxoutprod
ansible_user=ora19
oracle_home=/oracle/19
sql_plus=/oracle/19/bin/sqlplus

[XOUT_HB:children]
portal
pmc
web
activemq
modeshape
tobi

[XOUT_HB:vars]
ansible_user=xout-adm
ansible_ssh_private_key_file=/home/xout-adm/.ssh/xout-adm-hb

[all:vars]
#ansible_python_interpreter=/usr/bin/python3
xout_environment=HB_PRODUKTION
repo=/work/dms/rollout
udu_context=PROD
kasse=AHB
