[modeshape]
STEST-D2040 ansible_host=10.15.210.40 mode_user=tech_modeshape mode_pass=passwd
[pmc]
STEST-D2041 ansible_host=10.15.210.41
[portal]
STEST-D2042 ansible_host=10.15.210.42
[web]
STEST-D2041 ansible_host=10.15.210.41
[activemq]
STEST-D2041 ansible_host=10.15.210.41
[batchsplitter]
[tobi]
STEST-D2042 ansible_host=10.15.210.42

[ora_db]
VBLDIOR-D1134 ansible_host=fxoutt.oracle.ahbint.aok

[ora_db:vars]
# oracle_port=1533
oracle_user=p_config
oracle_pass=password
oracle_sid=fxoutt
ansible_user=ora19
oracle_home=/oracle/19
sql_plus=/oracle/19/bin/sqlplus

[XOUT_HB:children]
modeshape
pmc
portal
web
activemq
batchsplitter
tobi

[XOUT_HB:vars]
ansible_user=xout-adm
ansible_ssh_private_key_file=/home/xout-adm/.ssh/xout-adm-hb
ansible_python_interpreter=/usr/bin/python3.12
[all:vars]
xout_environment=HB_TEST
repo=/work/dms/rollout
udu_context=TEST
kasse=AHB
