[modeshape]
SPROD-1F130  ansible_host=10.17.31.130
[activemq]
SPROD-1F131  ansible_host=10.17.31.131
SPROD-1F132  ansible_host=10.17.31.132
[pmc]
SPROD-1F131  ansible_host=10.17.31.131
SPROD-1F132  ansible_host=10.17.31.132
SPROD-1F133  ansible_host=10.17.31.133
[portal]
SPROD-1F134  ansible_host=10.17.31.134
SPROD-1F135  ansible_host=10.17.31.135
SPROD-1F136  ansible_host=10.17.31.136
SPROD-1F17  ansible_host=10.17.31.17
SPROD-1F138  ansible_host=10.17.31.138
SPROD-1F139  ansible_host=10.17.31.139
SPROD-1F140  ansible_host=10.17.31.140
SPROD-1F141  ansible_host=10.17.31.141
SPROD-1F142  ansible_host=10.17.31.142
[web]
SPROD-1F143  ansible_host=10.17.31.143
[batchsplitter]
SPROD-1F134  ansible_host=10.17.31.134
[tobi]
SPROD-1F135  ansible_host=10.17.31.135

[ora_db]
VNLD-OR-29042 ansible_host=nxoutp.oracle.ands.aok

[ora_db:vars]
oracle_user=p_config
oracle_pass=password
oracle_sid=nxoutp
ansible_user=ora19
oracle_home=/oracle/19
sql_plus=/oracle/19/bin/sqlplus

[XOUT_NDS:children]
modeshape
pmc
portal
web
activemq
batchsplitter
tobi

[all:vars]
ansible_user=xout-adm
ansible_ssh_private_key_file=/home/xout-adm/.ssh/xout-adm-nds
#ansible_python_interpreter=/usr/bin/python3
xout_environment=NDS_PRODUKTION
repo=/work/dms/rollout
udu_context=PROD
kasse=ANDS
=PROD
kasse=ANDS
