---
# - name: Stop Pegasus (Druck Client)
#   shell: /software/00_Dev/xout/run_sql.py "xout_config_{{ xout_environment.lower() }}" "update pegasus_plugins set active=0 where TYPE=4"
#   args:
#    executable: /bin/bash
#   delegate_to: localhost
#   run_once: true
#   tags: 
#     - xout_stop
#     - pegasus_stop

- name: Stop Pegasus (Druck Client)
  include_tasks: 00_execute_sql.yml
  vars:
   sql_query: "update pegasus_plugins set active=0 where TYPE=4"
  run_once: true
  tags: 
    - xout_stop
    - pegasus_stop

# - name: Package Fakten sammeln
  # package_facts:
    # manager: auto
  # tags: 
    # - xout_stop
    # - zypper_refresh

- name: Fetch JSON Data from XOUT-Portal URL
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:5000/jolokia/read/portal.server.modules:*/CurrentModuleInformation"
    method: GET
    return_content: yes
  register: json_response
  when: "'portal' in group_names"
  tags: xout_stop

- name: Extract Modules Information from XOUT-Portal
  ansible.builtin.set_fact:
    modules: "{{ json_response.json.value }}"
  when: "'portal' in group_names"
  tags: xout_stop

- name: Stop Import, Router, Merger Modules
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:5000/jolokia/"
    method: POST
    headers:
      Content-Type: "text/plain"
    body_format: json
    body: "{{ '{\"mbean\": \"portal.server.modules:module=\\\"' + item.key.split('=')[1] | replace('\"', '') + '\\\"\", \"arguments\": [\"localhost/127.0.0.1\"], \"type\": \"EXEC\", \"operation\": \"stopModule\"}' }}"
  loop: "{{ modules | dict2items }}"
  when: >
    'portal' in group_names and 
    item.value.CurrentModuleInformation.state == 'RUNNING' and
    (
      'import' in item.key.split('=')[1].lower() or
      'router' in item.key.split('=')[1].lower() or
      'merger' in item.key.split('=')[1].lower() 
    )
  loop_control:
    label: "{{ item.key.split('=')[1] }}"
  tags: xout_stop
  ignore_errors: true

#- name: Stop Remaining Modules
#  ansible.builtin.uri:
#    url: "http://{{ ansible_host }}:5000/jolokia/"
#    method: POST
#    headers:
#      Content-Type: "text/plain"
#    body_format: json
#    body: "{{ '{\"mbean\": \"portal.server.modules:module=\\\"' + item.key.split('=')[1] | replace('\"', '') + '\\\"\", \"arguments\": [\"localhost/127.0.0.1\"], \"type\": \"EXEC\", \"operation\": \"stopModule\"}' }}"
#  loop: "{{ modules | dict2items }}"
#  when: >
#    'portal' in group_names and
#    item.value.CurrentModuleInformation.state == 'RUNNING' and
#    'import' not in item.key.split('=')[1].lower() and
#    'router' not in item.key.split('=')[1].lower() and
#    'merger' not in item.key.split('=')[1].lower()
#  loop_control:
#    label: "{{ item.key.split('=')[1] }}"
#  tags: xout_stop
#  ignore_errors: true
