---
- name: Überprüfe, ob der udu Ordner vorhanden ist
  stat:
    path: "/software/Xout/01_Releases/Auslieferung_{{ INSTALLVERSION }}/{{ kasse }}/udu"
  register: udu_folder
  run_once: yes
  delegate_to: localhost

- name: Pause for user confirmation about UDU installation
  pause:
    prompt: "UDU Update gefunden. Nach dem Installation drücke Enter, um fortzufahren"
  when: udu_folder.stat.exists
