---
# - name: Add and enable xout-repo Zypper Repository
#   #become: yes  # This will use sudo to escalate privileges
#   become_user: xout-adm
#   become_method: su
#   ansible.builtin.zypper_repository:
#     name: xout-repo
#     repo: "file://{{ repo }}"
#     state: present
#     enabled: yes
#     runrefresh: yes  # This will refresh the repository
#     autorefresh: no  # Deaktiviert autorefresh 
#     disable_gpg_check: yes  # Deaktiviert gpgcheck
#   #async: 300  # Erlaubt dem Task, bis zu 300 Sekunden im Hintergrund zu laufen
#   #poll: 0
#   register: zypper_repo_async_result
#   tags: 
#     - zypper_refresh

# - name: Warten auf die Vollendung des Zypper Repository refresh Tasks
#   ansible.builtin.async_status:
#     jid: "{{ zypper_repo_async_result.ansible_job_id }}"
#   register: final_result
#   until: final_result.finished | default(false) | bool
#   retries: 40  # Maximale Anzahl von Versuchen
#   delay: 15    # Verzögerung zwischen den Versuchen in Sekunden
#   tags: 
#     - zypper_refresh

 - name: Zypper add repository and refresh
   shell: | 
       sudo /usr/bin/zypper addrepo --check --refresh --name 'xout-rollout-repo' /work/dms/ xout-repo
       sudo zypper mr -e xout-repo
       sudo /usr/bin/zypper refresh -r xout-repo
   args:
       executable: /bin/bash
   when: "'XOUT_HB' in group_names or 'XOUT_NDS' in group_names"
   tags: 
     - zypper_refresh

# - name: Zypper-Repository hinzufügen und aktualisieren
#  community.general.zypper_repository:
#    name: xout-repo
#    repo: file:/work/dms/
#    description: xout-rollout-repo
#    state: present
#    enabled: yes
#    autorefresh: yes
#    runrefresh: yes
#  become: yes
#  when: "'XOUT_HB' in group_names or 'XOUT_NDS' in group_names"
#  tags:
#    - zypper_refresh
