---
#- name: Warte 15 Sekunden
#  ansible.builtin.pause:
#    seconds: 15
#  tags: xout_start

# Das Starten der Module ist unnötig, da diese mit dem Portal mitstarten - SL

#- name: Fetch JSON Data from XOUT-Portal URL
#  ansible.builtin.uri:
#    url: "http://{{ ansible_host }}:5000/jolokia/read/portal.server.modules:*/CurrentModuleInformation"
#    method: GET
#    return_content: yes
#  register: json_response
#  when: "'portal' in group_names"
#  tags: xout_start
#
#- name: Extract Modules Information from XOUT-Portal
#  ansible.builtin.set_fact:
#    modules: "{{ json_response.json.value }}"
#  when: "'portal' in group_names"
#  tags: xout_start
#
#- name: Start XOUT-Portal Modules Based on State Shutdown
#  ansible.builtin.uri:
#    url: "http://{{ ansible_host }}:5000/jolokia/"
#    method: POST
#    headers:
#      Content-Type: "text/plain"
#    body_format: json
#    body: "{{ '{\"mbean\": \"portal.server.modules:module=\\\"' + item.key.split('=')[1] | replace('\"', '') + '\\\"\", \"arguments\": [\"localhost/127.0.0.1\"], \"type\": \"EXEC\", \"operation\": \"startModule\"}' }}"
#  loop: "{{ modules | dict2items }}"
#  when: "'portal' in group_names"
#  loop_control:
#    label: "{{ item.key.split('=')[1] }}"
#  tags: xout_start

- name: Start Pegasus (Druck Client)
  include_tasks: 00_execute_sql.yml
  vars:
   sql_query: "update pegasus_plugins set active=1 where TYPE=4"
  run_once: true
  tags: 
    - xout_start
    - pegasus_start
